### ISSUE TITLE
Code not working for me

### ISSUE THREAD

**Issue by FJTamayo** [MorGuux/PaddleClutch#1]
I copy and pasted your code for my arduino pro micro.... And the left paddle is seen by the Arduino serial monitor, but it is not changing the clutch output value. Windows is interpreting the signal as a button basically, so the output is registering as either 0 or 100%, and again, it's only recognizing the right paddle. 
I'm stumped. What can I do?

**Comment by MorGuux** [comment]
Have you tried one of the example sketches I provided (for either a button or potentiometer bite point)? You may be missing a line of code that sets the range or bite point or similar.

**Comment by FJTamayo** [comment]
Got it working! The code wasn't working with the right paddle, as in: it would show values on the serial monitor, but wouldn't do anything for the clutch output. It all got fixed by changing the range of the pots, to be specific, this was the range I found on serial monitor:
PaddleClutchManager.setLeftPaddleRange(283, 412);

  PaddleClutchManager.setRightPaddleRange(400, 524);

Right now the issue i am having is the speed of the communication... It's laggy. I'll try to connect it directly to the PC. Plan b is to remove the serial comms

**Comment by MorGuux** [comment]
The serial comms aren't necessary so feel free to remove that. What appears to be laggy? Are you trying to handle it wirelessly?

**Comment by FJTamayo** [comment]
USB connection. Laggy as in it takes about a second from the moment I press the button to the moment the PC sees it. During my testing removing the serial comms fixed it

**Comment by MorGuux** [comment]
Nice. I'll close this then. Anything else let me know ;)
